Dynamic gas price
klaytn/klaytn pull request #1370
Opened 2022-05-12 08:03 UTC by kjeom

## Proposed changes

- Describe your changes to communicate to the maintainers why we should accept this pull request.
- If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

Please put an x in the boxes related to your change.

- [ ] Bugfix
- [x] New feature or enhancement
- [ ] Others

## Checklist

*Put an x in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.*

- [x] I have read the [CONTRIBUTING GUIDELINES](https://github.com/klaytn/klaytn/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla-assistant.io/klaytn/klaytn)
- [x] Lint and unit tests pass locally with my changes (`$ make test`)
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Related issues

- https://github.com/klaytn/kips/issues/71

2022-05-12 08:43 UTC, sirano11 commented on params/config.go
> +	LowerBoundBaseFee      uint64   `json:"lowerboundbasefee"`      // minimum base fee for dynamic gas price
```suggestion
	LowerBoundBaseFee      uint64   `json:"lowerboundbasefee"`      // Minimum base fee for dynamic gas price
```

2022-05-12 08:44 UTC, sirano11 commented on params/config.go
> +	UpperBoundBaseFee      uint64   `json:"upperboundbasefee"`      // maximum base fee for dynamic gas price
```suggestion
	UpperBoundBaseFee      uint64   `json:"upperboundbasefee"`      // Maximum base fee for dynamic gas price
```

2022-05-12 08:46 UTC, sirano11 commented on params/config.go
> +	GasTarget              uint64   `json:"gastarget"`              // guage parameter increasing or decreasing gas price
```suggestion
	GasTarget              uint64   `json:"gastarget"`              // Gauge parameter increasing or decreasing gas price
```

2022-05-12 08:52 UTC, sirano11 commented on params/config.go
> +	BlockGasLimit          uint64   `json:"blockgaslimit"`          // maximum network and process capacity to allow in a block
```suggestion
	BlockGasLimit          uint64   `json:"blockgaslimit"`          // Maximum network and process capacity to allow in a block
```

2022-05-12 08:53 UTC, sirano11 commented on params/config.go
> +	BaseFeeDenominator     uint64   `json:"basefeedenominator"`     // for nomalizing effect of the rapid change like impulse gas used
```suggestion
	BaseFeeDenominator     uint64   `json:"basefeedenominator"`     // For normalizing effect of the rapid change like impulse gas used
```

2022-05-13 00:44 UTC, sirano11 commented on governance/default.go
> +		params.LowerBoundBaseFee:       "reward.lowerboundbasefee",
How about renaming key?

2022-05-13 05:37 UTC, blukat29 requested changes

2022-05-13 05:37 UTC, blukat29 commented on governance/handler.go
> +
Please do not modify `Governance.ChainConfig`. It is intended to store the initial chain config.

What can change is BlockChain.chainConfig. If you want to edit BlockChain.chainConfig, then you should do similar to https://github.com/klaytn/klaytn/blob/v1.8.3/blockchain/blockchain.go#L429. and https://github.com/klaytn/klaytn/blob/v1.8.3/governance/handler.go#L80.

```go
// blockchain/blockchain.go
func (bc *BlockChain) GasTarget() uint64 { ... }
func (bc *BlockChain) SetGasTarget(val uint64) { ... }

// governance/handler.go
func updateBlockGasLimit(g *Governance, k string, v interface{}) {
	if g.blockChain != nil {
		g.blockChain.SetGasTarget(g.GetGovernanceValue(params.GasTarget).(uint64))
	}
}
```

2022-05-16 04:56 UTC, kjeom commented
closed by corrupted rebase

2022-05-16 04:56 UTC, closed without merging